env: "dev"
storage_path: "./storage/sso.db"
token_ttl: 2h

grpc:
  port: 44044
  timeout: 30s

http_server:
  address: 0.0.0.0:8082
  timeout: 4s
  idle_timeout: 60s
  
db:
  host: db_auth
  port: 5432
  user: admin
  password: root
  dbname: admin